export const MOOD_LIMITS = {
  DOMINANT_EMOTIONS: 5,
  TAGS: 8,
  PEOPLE_PRESENT: 10,
  MAX_MOOD_LEVEL: 10,
  MAX_ENERGY_LEVEL: 10,
} as const;

export const AI_LIMITS = {
  MAX_TOKENS_HARD_LIMIT: 8192,
  DEFAULT_TOKENS: 512,
  MAX_RETRIES: 5,
  BACKOFF_BASE_MS: 250,
  RATE_LIMIT_WINDOW_MS: 60000,
  RATE_LIMIT_MAX_REQUESTS: 50,
  RATE_LIMIT_KEY_HASH_LENGTH: 8,
  USER_INPUT_MAX_LENGTH: 5000,
  USER_TEXT_MAX_LENGTH: 50000,
} as const;

export const TYPEWRITER_DELAYS = {
  SLOW: 90,
  NORMAL: 50,
  FAST: 25,
  MAX_DURATION_MS: 4000,
  PAUSE_MULTIPLIERS: {
    COMMA: 3, // virgules, points-virgules, deux-points (150ms pour normal)
    SENTENCE: 6, // points, points d'exclamation, points d'interrogation (300ms)
    NEWLINE: 10, // nouvelles lignes (500ms)
  },
} as const;

export const REGEX_PATTERNS = {
  GPT5_MODEL: /^gpt-5/i,
  DATE_HEADING: /^#{1,6}\s*\d{4}-\d{2}-\d{2}\s*$/,
  HEADING: /^\s*#{1,6}\s*.+$/,
  SPEAKER_LINE: /^[^\s].*:\s*$/,
  FRONTMATTER_DELIMITER: /^---$/,
} as const;

export const CSS_CLASSES = {
  NOVA_DEEPEN: 'nova-deepen',
  NOVA_MOOD_ANALYZE: 'nova-mood-analyze',
} as const;

export const API_CONFIG = {
  OPENAI_CHAT_URL: 'https://api.openai.com/v1/chat/completions',
  OPENAI_EMBEDDINGS_URL: 'https://api.openai.com/v1/embeddings',
  OPENAI_MODELS_URL: 'https://api.openai.com/v1/models',
  TIMEOUT_MS: 10000,
  USER_AGENT: 'Nova-Journal-Plugin/1.0',
  MAX_REQUEST_SIZE_BYTES: 2000000, // ~2MB
  HTTP_UNAUTHORIZED: 401,
  HTTP_RATE_LIMIT: 429,
  HTTP_SERVER_ERROR: 500,
} as const;

export const TEMPLATE_PATTERNS = {
  PROMPT: /\{\{\s*prompt\s*\}\}/g,
  USER_LINE: /\{\{\s*user_line\s*\}\}/g,
  DATE: /\{\{\s*date(?::([^}]+))?\s*\}\}/g,
  MULTIPLE_NEWLINES: /\n{3,}/g,
} as const;

// File and Content Limits
export const FILE_LIMITS = {
  MAX_FILE_SIZE_BYTES: 1024 * 1024, // 1MB
  MAX_CLIPBOARD_SIZE_BYTES: 1024 * 1024, // 1MB
  MAX_IMPORT_CONTENT_LENGTH: 1024 * 1024, // 1MB
} as const;

// Content Analysis and Processing
export const CONTENT_LIMITS = {
  MIN_CONTENT_LENGTH: 50,
  MIN_SUBSTANTIAL_LENGTH: 100,
  MIN_CONTENT_FOR_ANALYSIS: 100,
  PREVIEW_LENGTH: 200,
  MAX_CONTENT_PREVIEW: 250,
  MAX_CONTENT_DISPLAY: 300,
  CHUNK_CONTENT_MIN: 50,
  USER_SECTION_MIN_LENGTH: 20,
  CONTENT_EXCERPT_MAX: 200,
  TRIMMED_CONTENT_MAX: 5000,
  // Mood analysis specific
  NOTE_EXCERPT_MAX_LENGTH: 200,
  MIN_MEANINGFUL_CONTENT: 10,
} as const;

// Time and Date Constants
export const TIME_CONSTANTS = {
  MS_PER_SECOND: 1000,
  MS_PER_MINUTE: 60 * 1000,
  MS_PER_HOUR: 60 * 60 * 1000,
  MS_PER_DAY: 24 * 60 * 60 * 1000,
  DAYS_IN_WEEK: 7,
  DAYS_IN_MONTH: 30,
  MONTHS_IN_YEAR: 12,
  RECENT_DAYS_LIMIT: 3,
  WEEK_DAYS_LIMIT: 7,
  MONTH_DAYS_LIMIT: 30,
  DEFAULT_ANALYSIS_DAYS: 7,
  // RAG time calculations
  VERY_RECENT_DAYS_LIMIT: 2,
  TIME_AGO_DAYS_MIN: 0,
  TIME_AGO_DAYS_ONE: 1,
  TIME_AGO_WEEKS_LIMIT: 4,
  TIME_AGO_MONTHS_LIMIT: 12,
  // Date parsing defaults
  DEFAULT_HOUR: '00',
  DEFAULT_MINUTE: '00',
  DEFAULT_SECOND: '00',
} as const;

// API and Security Validation
export const VALIDATION_LIMITS = {
  API_KEY_MIN_LENGTH: 20,
  API_KEY_MIN_PATTERN_LENGTH: 10,
  SECRET_MIN_LENGTH: 8,
  HASH_MIN_LENGTH: 32,
  ENCODED_DATA_MIN_LENGTH: 20,
  STRING_FIELD_MAX_LENGTH: 50,
  SECTION_HEADING_MAX_LENGTH: 100,
  FOLDER_PATH_MAX_LENGTH: 200,
  API_KEY_MAX_LENGTH: 500,
  SYSTEM_PROMPT_MAX_LENGTH: 2000,
  FOLDER_NAME_MAX_LENGTH: 300,
} as const;

// UI and Display Constants
export const UI_CONSTANTS = {
  TEXTAREA_ROWS_SMALL: 3,
  TEXTAREA_ROWS_MEDIUM: 4,
  TEXTAREA_COLS_DEFAULT: 40,
  LOADING_DOTS_COUNT: 3,
  PERCENTAGE_FULL: 100,
  Z_INDEX_MODAL: 1000,
  FONT_SIZE_SMALL: 11,
  FONT_SIZE_NORMAL: 12,
  HEIGHT_SMALL: 200,
  HEIGHT_MEDIUM: 300,
} as const;

// Hash and Encryption Constants
export const HASH_CONSTANTS = {
  BIT_SHIFT_LEFT: 5,
  HASH_SEED_BASE: 0,
  RANDOM_STRING_LENGTH: 8,
  RANDOM_STRING_START: 2,
} as const;

// Embedding and Vector Processing
export const EMBEDDING_CONFIG = {
  DEFAULT_CHUNK_SIZE: 200,
  DEFAULT_OVERLAP: 50,
  CHUNK_SIZE_ALTERNATIVE: 250,
  OVERLAP_ALTERNATIVE: 75,
  MAX_CHUNKS_PER_BATCH: 50,
  MAX_CHUNKS_LARGE_BATCH: 100,
  MAX_DAYS_INDEX: 180,
  DEFAULT_K_RESULTS: 5,
  EMOTIONAL_SEARCH_K: 3,
  THEMATIC_SEARCH_K: 4,
  TEMPORAL_SEARCH_K: 2,
  BROAD_SEARCH_LIMIT: 25,
  EXTENDED_SEARCH_LIMIT: 50,
  TOP_K_DEFAULT: 3,
} as const;

// Context and RAG Processing
export const CONTEXT_LIMITS = {
  MAX_CONTEXT_CHUNKS: 8,
  DEFAULT_MAX_CHUNKS: 5,
  RECENT_CHUNKS_LIMIT: 3,
  HISTORICAL_CHUNKS_LIMIT: 5,
  COMBINED_CHUNKS_MAX: 12,
  RECENT_SEARCH_LIMIT: 15,
  BROAD_SEARCH_CHUNKS: 25,
  EXTENDED_SEARCH_CHUNKS: 50,
  WORD_LENGTH_MIN: 3,
  WORD_LENGTH_MAX: 15,
  SENTENCE_WORDS_MAX: 5,
  EXPANDED_TERMS_MAX: 5,
  TOP_WORDS_MAX: 3,
  MIN_WORD_COUNT: 1,
  // RAG-specific thresholds
  MIN_CONTENT_LENGTH_RAG: 100,
  MIN_SUBSTANTIAL_LENGTH_RAG: 200,
  EMPTY_PROMPT_MAX_LENGTH: 300,
  MARKUP_HEAVY_MAX_LENGTH: 500,
  MAX_BUTTONS_ALLOWED: 2,
  PREVIEW_LENGTH_RAG: 500,
  USER_SECTION_MIN_LENGTH_RAG: 20,
  USER_SECTION_MAX_CAPTURE_RAG: 1000,
} as const;

// Search and Filtering
export const SEARCH_CONSTANTS = {
  DIVERSITY_THRESHOLD_DEFAULT: 0.3,
  DIVERSITY_THRESHOLD_STRICT: 0.4,
  DIVERSITY_THRESHOLD_RELAXED: 0.5,
  DIVERSITY_THRESHOLD_MINIMAL: 0.05,
  RECENCY_BOOST_DIVISOR: 7,
  EXACT_MATCH_BOOST: 1.3,
  WEEKS_IN_MONTH: 4,
  MONTHS_IN_YEAR: 12,
  // Score boosting constants
  RECENCY_BOOST_MULTIPLIER: 0.2,
  CONTEXT_TYPE_BOOST: 1.1,
  BASE_SCORE_MULTIPLIER: 1,
  MIN_RESULT_INDEX: 0,
} as const;

// Timing and Delays
export const TIMING_CONFIG = {
  FILE_OPERATION_DELAY: 100,
  EMBEDDING_MIGRATION_DELAY: 3000,
  TOAST_TIMEOUT_DEFAULT: 5000,
  TOAST_TIMEOUT_SHORT: 3000,
  TOAST_TIMEOUT_ERROR: 5000,
  NOTIFICATION_TIMEOUT: 5000,
} as const;

// Token and AI Limits
export const TOKEN_LIMITS = {
  PROMPT_MAX_TOKENS: 60,
  STYLE_SELECTOR_MAX_TOKENS: 200,
  PROMPT_MAX_WORDS: 25,
  ENHANCED_PROMPT_MAX_WORDS: 30,
  CONCISE_RESPONSE_SENTENCES: 3,
} as const;

// Regex Pattern Constants
export const PATTERN_CONSTANTS = {
  HEADING_MIN_LEVEL: 1,
  HEADING_MAX_LEVEL: 6,
  YEAR_DIGITS: 4,
  MONTH_DIGITS: 2,
  DAY_DIGITS: 2,
  HOUR_DIGITS: 2,
  MINUTE_DIGITS: 2,
  USER_SECTION_MAX_CAPTURE: 1000,
} as const;

// Parsing and Processing Constants
export const PARSING_CONSTANTS = {
  FRONTMATTER_START_INDEX: 0,
  FRONTMATTER_SEARCH_START: 0,
  FRONTMATTER_LINE_AFTER_START: 1,
  FRONTMATTER_NEXT_LINE_OFFSET: 1,
  ARRAY_BRACKET_TRIM_START: 1,
  ARRAY_BRACKET_TRIM_END: -1,
  STRING_NEXT_CHAR_OFFSET: 1,
} as const;

export const EXCLUDED_NAMES = new Set(['nova', 'ai', 'assistant', 'you', 'me']);
export const VALID_SENTIMENTS = ['positive', 'neutral', 'negative'] as const;
export const FRONTMATTER_ORDER = ['mood_emoji', 'sentiment', 'dominant_emotions', 'tags', 'people_present'] as const;
